// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0D64HiV-2veRaKkB6flmKrVAXxcZLwUo',
    appId: '1:985821235413:web:278571b734eccb525bfa5c',
    messagingSenderId: '985821235413',
    projectId: 'is-it-safe-29b67',
    authDomain: 'is-it-safe-29b67.firebaseapp.com',
    storageBucket: 'is-it-safe-29b67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWZH7HNZBosSg6e5Y8EgEzHhrBewrIPUE',
    appId: '1:985821235413:android:5d385f55399863c75bfa5c',
    messagingSenderId: '985821235413',
    projectId: 'is-it-safe-29b67',
    storageBucket: 'is-it-safe-29b67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmtdeJQKxoPmj0ljT_Nrf4xzDxM0BrT-s',
    appId: '1:985821235413:ios:bb3376032fb9cf855bfa5c',
    messagingSenderId: '985821235413',
    projectId: 'is-it-safe-29b67',
    storageBucket: 'is-it-safe-29b67.appspot.com',
    iosBundleId: 'com.example.isItSafeApp',
  );
}
