name: Develop CI/CD

on:
  push:
    branches:
      - dev

jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
          
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        
      - name: Create version.txt with nuGetVersion
        run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt

      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt
      
  build:
    name: Create Android Build
    needs: version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion
          
      - name: Create new file without newline char from version.txt
        run: tr -d '\n' < version.txt > version1.txt
      
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version1.txt
      
      - name: Update version in YAML
        run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
          
      # - name: Decode Keystore
      #   env:
      #      ENCODED_STRING: ${{ secrets.ANDROID_KEYSOTRE_BASE64 }}
      #      STORE_FILE: ${{ secrets.STORE_FILE }}
 
      #   run: |
      #      echo $ENCODED_STRING > keystore-b64.txt
      #      base64 -d keystore-b64.txt > $STORE_FILE
          
      # - name: Create key.properties
      #   run: |
      #     echo "storeFile=${{ secrets.STORE_FILE }}" > android/key.properties
      #     echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
      #     echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
      #     echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.5'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage
      
      - name: Upload to code coverage
        uses: codecov/codecov-action@v3
        with:
         token: ${{secrets.CODECOV_TOKEN}}
         file: coverage/lcov.info

      - name: Build Android Release App
        # env:
        #    STORE_FILE: ${{ secrets.STORE_FILE }}
        #    KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        #    KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        #    STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: flutter build apk -t lib/main_dev.dart --release

      - name: Rename Artifact
        run: mv build/app/outputs/flutter-apk/*.apk build/app/outputs/flutter-apk/app-$GITHUB_ISSUE_NUMBER-debug.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-$GITHUB_ISSUE_NUMBER-debug
          path: build/app/outputs/flutter-apk/app-$GITHUB_ISSUE_NUMBER-debug.apk
