name: Release CI/CD

on:
  push:
    branches:
      - release
    tags:
      # Only build for tags that follow semantic versioning
      - 'v[0-9]+.[0-9]+.[0-9]+[0-9]'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          # Use the latest Flutter version available
          flutter-version: 3.7.8

      # Install dependencies
      - name: Get dependencies
        run: flutter pub get

      # Run tests
      - name: Run tests
        run: flutter test
      
      # Build App Bundle
      - name: Build Prod App Bundle
        run: flutter build appbundle -t lib/main.dart --release --flavor prod
      
      # Upload App Bundle
      - name: Upload Prod App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-prod-release
          path: build/app/outputs/bundle/prodRelease/app-prod-release.aab
