name: Release CI/CD

on:
  push:
    branches:
      - release
    tags:
      # Only build for tags that follow semantic versioning
      - 'v[0-9]+.[0-9]+.[0-9]+[0-9]'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          # Use the latest Flutter version available
          flutter-version: 3.7.8

      # Install dependencies
      - name: Get dependencies
        run: flutter pub get

      # Run tests
      - name: Run tests
        run: flutter test

      # Build APK
      - name: Build APK
        run: flutter build apk

      # Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      # Send message to Discord webhook

#       - name: Send message to Discord
#         env:
#           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
#         uses: Ilshidur/action-discord@master
#         with:
#           args: "New version available"
